const EVENT_TYPES = {
  CREATOR_APP_SUBMITTED: "CREATOR_APP_SUBMITTED",
  CREATOR_APP_APPROVED: "CREATOR_APP_APPROVED",
  CREATOR_APP_REJECTED: "CREATOR_APP_REJECTED",
  CREATOR_APP_REQUEST_INFO: "CREATOR_APP_REQUEST_INFO",
};

const EVENT_CATEGORIES = {
  CREATOR: "CREATOR",
};

module.exports = { EVENT_TYPES, EVENT_CATEGORIES };
