USE [CREATOR_SERVICE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ============================================================
-- USP_CATALOG_SEARCH
-- Search published plans with filters, sorting, and pagination.
-- ============================================================
CREATE OR ALTER PROCEDURE [dbo].[USP_CATALOG_SEARCH]
(
    @SEARCHTERM NVARCHAR(200) = NULL,
    @TAGS       NVARCHAR(500) = NULL,
    @CATEGORY   NVARCHAR(50)  = NULL,
    @DIFFICULTY NVARCHAR(20)  = NULL,
    @SORTBY     NVARCHAR(20)  = 'RECENT',
    @PAGESIZE   INT           = 20,
    @PAGENUMBER INT           = 1
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @OFFSET INT = (@PAGENUMBER - 1) * @PAGESIZE;

    -- Materialize tag filter list
    DECLARE @TAGFILTER TABLE (TAG NVARCHAR(100));
    IF @TAGS IS NOT NULL
    BEGIN
        INSERT INTO @TAGFILTER (TAG)
        SELECT TRIM(value) FROM STRING_SPLIT(@TAGS, ',')
        WHERE TRIM(value) != '';
    END

    ;WITH Base AS (
        SELECT
            P.PLANID, P.TITLE, P.SHORTDESCRIPTION, P.CATEGORY,
            P.DIFFICULTY, P.DURATIONDAYS, P.THEMECOLORHEX,
            P.COVERFILEUUID, P.PLANICONEMOJI,
            P.PUBLISHEDAT, P.CREATEDDATE,
            CP.DISPLAYNAME  AS CREATORDISPLAYNAME,
            CP.AVATARFILEUUID AS CREATORAVATAR,
            R.AVGRATING, R.REVIEWCOUNT, R.ENROLLCOUNT, R.COMPLETIONPERCENT
        FROM dbo.STUDY_PLAN P
        LEFT JOIN dbo.CREATOR_PROFILE CP ON P.CREATORUSERID = CP.USERID
        LEFT JOIN dbo.STUDY_PLAN_CATALOG_ROLLUP R
            ON P.PLANID = R.PLANID AND R.PLANVERSION = P.CURRENTVERSIONNO AND R.ISACTIVE = 1
        WHERE P.PLANSTATUS = 'PUBLISHED'
          AND (@SEARCHTERM IS NULL
               OR P.TITLE LIKE '%' + @SEARCHTERM + '%'
               OR P.SHORTDESCRIPTION LIKE '%' + @SEARCHTERM + '%')
          AND (@CATEGORY IS NULL OR P.CATEGORY = @CATEGORY)
          AND (@DIFFICULTY IS NULL OR P.DIFFICULTY = @DIFFICULTY)
          AND (
              @TAGS IS NULL
              OR EXISTS (
                  SELECT 1 FROM dbo.STUDY_PLAN_TAG T
                  WHERE T.PLANID = P.PLANID AND T.TAG IN (SELECT TAG FROM @TAGFILTER)
              )
          )
    )
    SELECT
        COUNT(*) OVER() AS TOTALCOUNT,
        PLANID, TITLE, SHORTDESCRIPTION, CATEGORY,
        DIFFICULTY, DURATIONDAYS, THEMECOLORHEX,
        COVERFILEUUID, PLANICONEMOJI,
        PUBLISHEDAT, CREATEDDATE,
        CREATORDISPLAYNAME, CREATORAVATAR,
        AVGRATING, REVIEWCOUNT, ENROLLCOUNT, COMPLETIONPERCENT
    FROM Base
    ORDER BY
        CASE @SORTBY
            WHEN 'RATING'  THEN AVGRATING
            WHEN 'POPULAR' THEN CAST(ENROLLCOUNT AS DECIMAL(18,2))
            ELSE NULL
        END DESC,
        CASE WHEN @SORTBY = 'RECENT' THEN PUBLISHEDAT END DESC,
        PLANID DESC
    OFFSET @OFFSET ROWS FETCH NEXT @PAGESIZE ROWS ONLY;
END
GO

-- ============================================================
-- USP_CATALOG_GET_PLAN_PUBLIC
-- Public detail view of a published plan (4 result sets).
-- ============================================================
CREATE OR ALTER PROCEDURE [dbo].[USP_CATALOG_GET_PLAN_PUBLIC]
(
    @PLANID BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @STATUS NVARCHAR(30);
    DECLARE @PLANVERSION INT;

    SELECT @STATUS = PLANSTATUS, @PLANVERSION = CURRENTVERSIONNO
    FROM dbo.STUDY_PLAN
    WHERE PLANID = @PLANID;

    IF @STATUS IS NULL
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan not found' AS MESSAGE;
        RETURN;
    END

    IF @STATUS != 'PUBLISHED'
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan is not published' AS MESSAGE;
        RETURN;
    END

    -- Result set 1: Plan metadata + creator info + rollup stats
    SELECT
        P.PLANID, P.CREATORUSERID, P.TITLE, P.SHORTDESCRIPTION, P.FULLDESCRIPTION,
        P.DURATIONDAYS, P.CATEGORY, P.DIFFICULTY, P.THEMECOLORHEX,
        P.COVERFILEUUID, P.BANNERFILEUUID, P.PLANICONEMOJI,
        P.PLANSTATUS, P.CURRENTVERSIONNO, P.PUBLISHEDAT,
        CP.DISPLAYNAME  AS CREATORDISPLAYNAME,
        CP.AVATARFILEUUID AS CREATORAVATAR,
        CP.PUBLICEMAIL  AS CREATORPUBLICEMAIL,
        R.AVGRATING, R.REVIEWCOUNT, R.ENROLLCOUNT, R.COMPLETIONPERCENT
    FROM dbo.STUDY_PLAN P
    LEFT JOIN dbo.CREATOR_PROFILE CP ON P.CREATORUSERID = CP.USERID
    LEFT JOIN dbo.STUDY_PLAN_CATALOG_ROLLUP R
        ON P.PLANID = R.PLANID AND R.PLANVERSION = P.CURRENTVERSIONNO AND R.ISACTIVE = 1
    WHERE P.PLANID = @PLANID;

    -- Result set 2: Tags
    SELECT TAG
    FROM dbo.STUDY_PLAN_TAG
    WHERE PLANID = @PLANID;

    -- Result set 3: Days for published version
    SELECT
        D.DAYID, D.DAYNUMBER, D.TITLE, D.NOTES
    FROM dbo.STUDY_PLAN_DAY D
    WHERE D.PLANID = @PLANID AND D.PLANVERSION = @PLANVERSION
    ORDER BY D.DAYNUMBER ASC;

    -- Result set 4: Slots for those days
    SELECT
        S.SLOTID, S.DAYID, S.SLOTTYPE, S.TITLE, S.DESCRIPTION,
        S.ESTIMATEDMINUTES, S.SORTORDER, S.TOPICID, S.CONTENTID,
        S.CONTENTFILEUUID, S.EXTERNALURL, S.QUIZJSON
    FROM dbo.STUDY_PLAN_SLOT S
    INNER JOIN dbo.STUDY_PLAN_DAY D ON S.DAYID = D.DAYID
    WHERE D.PLANID = @PLANID AND D.PLANVERSION = @PLANVERSION
    ORDER BY D.DAYNUMBER ASC, S.SORTORDER ASC;
END
GO
