USE [CREATOR_SERVICE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ============================================================
-- 11_PROFILE_PUBLISH_AND_LIST_STATS.sql
-- Fixes:
--   1) On APPROVE: upsert CREATOR_PROFILE from application prefs
--      (root cause of catalog "Unknown" creator name)
--   2) Publish validate: require ACTIVE profile with display name
--   3) List-by-creator: join catalog rollup for enroll/rating stats
--   4) Catalog public plan/search: include creator bio
--   5) Backfill profiles for approved creators / published plans
-- ============================================================

-- ------------------------------------------------------------
-- USP_CREATOR_APP_REVIEW (patched)
-- ------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[USP_CREATOR_APP_REVIEW]
(
    @APPLICATIONID     BIGINT,
    @ACTION            NVARCHAR(20),
    @REVIEWEDBYUSERID  BIGINT,
    @REVIEWNOTE        NVARCHAR(2000) = NULL,
    @REJECTIONREASON   NVARCHAR(2000) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        DECLARE @CURRENTSTATUS NVARCHAR(30);
        DECLARE @APPUSERID BIGINT;
        DECLARE @DISPLAYNAMEPREF NVARCHAR(100);
        DECLARE @BIODRAFT NVARCHAR(2000);

        SELECT
            @CURRENTSTATUS = STATUS,
            @APPUSERID = USERID,
            @DISPLAYNAMEPREF = DISPLAYNAMEPREF,
            @BIODRAFT = BIODRAFT
        FROM dbo.CREATOR_APPLICATION
        WHERE APPLICATIONID = @APPLICATIONID AND ACTIVE = 1;

        IF @CURRENTSTATUS IS NULL
        BEGIN
            SELECT 0 AS SUCCESS, NULL AS STATUS, 'Application not found' AS MESSAGE;
            RETURN;
        END

        IF @CURRENTSTATUS NOT IN ('SUBMITTED', 'UNDER_REVIEW')
        BEGIN
            SELECT 0 AS SUCCESS, @CURRENTSTATUS AS STATUS,
                   'Application is not in a reviewable state' AS MESSAGE;
            RETURN;
        END

        IF @ACTION NOT IN ('APPROVE', 'REJECT', 'REQUEST_INFO')
        BEGIN
            SELECT 0 AS SUCCESS, @CURRENTSTATUS AS STATUS,
                   'Invalid action. Use APPROVE, REJECT, or REQUEST_INFO' AS MESSAGE;
            RETURN;
        END

        DECLARE @NEWSTATUS NVARCHAR(30);
        SET @NEWSTATUS = CASE @ACTION
            WHEN 'APPROVE'      THEN 'APPROVED'
            WHEN 'REJECT'       THEN 'REJECTED'
            WHEN 'REQUEST_INFO' THEN 'REQUEST_INFO'
        END;

        UPDATE dbo.CREATOR_APPLICATION
        SET STATUS            = @NEWSTATUS,
            REVIEWEDBYUSERID  = @REVIEWEDBYUSERID,
            REVIEWEDAT        = SYSUTCDATETIME(),
            REVIEWNOTE        = @REVIEWNOTE,
            REJECTIONREASON   = CASE WHEN @ACTION = 'REJECT' THEN @REJECTIONREASON ELSE REJECTIONREASON END,
            UPDATEDDATE       = SYSUTCDATETIME()
        WHERE APPLICATIONID = @APPLICATIONID;

        -- Ensure a public-facing creator profile exists on approve so catalog
        -- LEFT JOIN CREATOR_PROFILE returns a display name (not NULL → "Unknown").
        IF @ACTION = 'APPROVE'
        BEGIN
            DECLARE @DN NVARCHAR(100) =
                NULLIF(LTRIM(RTRIM(@DISPLAYNAMEPREF)), N'');
            IF @DN IS NULL
                SET @DN = N'Creator ' + CAST(@APPUSERID AS NVARCHAR(30));

            IF EXISTS (SELECT 1 FROM dbo.CREATOR_PROFILE WHERE USERID = @APPUSERID)
            BEGIN
                UPDATE dbo.CREATOR_PROFILE
                SET DISPLAYNAME = CASE
                        WHEN DISPLAYNAME IS NULL OR LTRIM(RTRIM(DISPLAYNAME)) = N''
                        THEN @DN ELSE DISPLAYNAME
                    END,
                    BIO = CASE
                        WHEN (BIO IS NULL OR LTRIM(RTRIM(BIO)) = N'')
                             AND @BIODRAFT IS NOT NULL
                        THEN @BIODRAFT ELSE BIO
                    END,
                    PROFILESTATUS = N'ACTIVE',
                    UPDATEDDATE = SYSUTCDATETIME()
                WHERE USERID = @APPUSERID;
            END
            ELSE
            BEGIN
                INSERT INTO dbo.CREATOR_PROFILE
                (
                    USERID, DISPLAYNAME, BIO, EXPERTISETAGS, PUBLICEMAIL,
                    AVATARFILEUUID, COVERFILEUUID, WEBSITEURL,
                    PROFILESTATUS, CREATEDDATE, UPDATEDDATE
                )
                VALUES
                (
                    @APPUSERID, @DN, @BIODRAFT, NULL, NULL,
                    NULL, NULL, NULL,
                    N'ACTIVE', SYSUTCDATETIME(), SYSUTCDATETIME()
                );
            END
        END

        SELECT 1 AS SUCCESS, @NEWSTATUS AS STATUS, 'Review action applied' AS MESSAGE;
    END TRY
    BEGIN CATCH
        SELECT 0 AS SUCCESS, NULL AS STATUS, ERROR_MESSAGE() AS MESSAGE;
    END CATCH
END
GO

-- ------------------------------------------------------------
-- USP_STUDY_PLAN_PUBLISH_VALIDATE (patched — require profile)
-- ------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[USP_STUDY_PLAN_PUBLISH_VALIDATE]
(
    @PLANID        BIGINT,
    @CREATORUSERID BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @OWNERID BIGINT;
    DECLARE @STATUS  NVARCHAR(30);
    DECLARE @PLANVERSION INT;
    DECLARE @DURATIONDAYS INT;

    SELECT @OWNERID = CREATORUSERID,
           @STATUS  = PLANSTATUS,
           @PLANVERSION = CURRENTVERSIONNO,
           @DURATIONDAYS = DURATIONDAYS
    FROM dbo.STUDY_PLAN
    WHERE PLANID = @PLANID;

    IF @OWNERID IS NULL
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan not found' AS MESSAGE;
        RETURN;
    END

    IF @OWNERID != @CREATORUSERID
    BEGIN
        SELECT 0 AS SUCCESS, 'You do not own this plan' AS MESSAGE;
        RETURN;
    END

    IF @STATUS NOT IN ('DRAFT', 'READY_FOR_REVIEW')
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan must be in DRAFT or READY_FOR_REVIEW status' AS MESSAGE;
        RETURN;
    END

    IF NOT EXISTS (
        SELECT 1
        FROM dbo.CREATOR_PROFILE
        WHERE USERID = @CREATORUSERID
          AND PROFILESTATUS = N'ACTIVE'
          AND DISPLAYNAME IS NOT NULL
          AND LTRIM(RTRIM(DISPLAYNAME)) <> N''
    )
    BEGIN
        SELECT 0 AS SUCCESS,
               'Create your creator profile with a display name before publishing' AS MESSAGE;
        RETURN;
    END

    DECLARE @DAYCOUNT INT;
    SELECT @DAYCOUNT = COUNT(*)
    FROM dbo.STUDY_PLAN_DAY
    WHERE PLANID = @PLANID AND PLANVERSION = @PLANVERSION;

    IF @DAYCOUNT = 0
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan has 0 days' AS MESSAGE;
        RETURN;
    END

    DECLARE @EMPTYDAY INT;
    DECLARE @EMPTYDAYNUMBER INT;

    SELECT TOP 1 @EMPTYDAY = D.DAYID, @EMPTYDAYNUMBER = D.DAYNUMBER
    FROM dbo.STUDY_PLAN_DAY D
    LEFT JOIN dbo.STUDY_PLAN_SLOT S ON D.DAYID = S.DAYID
    WHERE D.PLANID = @PLANID AND D.PLANVERSION = @PLANVERSION
    GROUP BY D.DAYID, D.DAYNUMBER
    HAVING COUNT(S.SLOTID) = 0
    ORDER BY D.DAYNUMBER ASC;

    IF @EMPTYDAY IS NOT NULL
    BEGIN
        SELECT 0 AS SUCCESS,
               'Day ' + CAST(@EMPTYDAYNUMBER AS NVARCHAR(10)) + ' has no slots' AS MESSAGE;
        RETURN;
    END

    IF @DURATIONDAYS IS NOT NULL AND @DURATIONDAYS != @DAYCOUNT
    BEGIN
        SELECT 0 AS SUCCESS,
               'DURATIONDAYS (' + CAST(@DURATIONDAYS AS NVARCHAR(10))
               + ') does not match actual day count ('
               + CAST(@DAYCOUNT AS NVARCHAR(10)) + ')' AS MESSAGE;
        RETURN;
    END

    SELECT 1 AS SUCCESS, 'Validation passed' AS MESSAGE;
END
GO

-- ------------------------------------------------------------
-- USP_STUDY_PLAN_LIST_BY_CREATOR (patched — rollup stats)
-- ------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[USP_STUDY_PLAN_LIST_BY_CREATOR]
(
    @CREATORUSERID BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        P.PLANID, P.TITLE, P.SHORTDESCRIPTION, P.CATEGORY,
        P.DIFFICULTY, P.PLANSTATUS, P.CURRENTVERSIONNO,
        P.DURATIONDAYS, P.PLANICONEMOJI, P.THEMECOLORHEX,
        P.PUBLISHEDAT, P.CREATEDDATE, P.UPDATEDDATE,
        ISNULL(DC.DAYCOUNT, 0)  AS DAYCOUNT,
        ISNULL(SC.SLOTCOUNT, 0) AS SLOTCOUNT,
        R.ENROLLCOUNT,
        R.AVGRATING,
        R.REVIEWCOUNT,
        R.COMPLETIONPERCENT
    FROM dbo.STUDY_PLAN P
    OUTER APPLY (
        SELECT COUNT(*) AS DAYCOUNT
        FROM dbo.STUDY_PLAN_DAY D
        WHERE D.PLANID = P.PLANID AND D.PLANVERSION = P.CURRENTVERSIONNO
    ) DC
    OUTER APPLY (
        SELECT COUNT(*) AS SLOTCOUNT
        FROM dbo.STUDY_PLAN_SLOT S
        INNER JOIN dbo.STUDY_PLAN_DAY D2 ON S.DAYID = D2.DAYID
        WHERE D2.PLANID = P.PLANID AND D2.PLANVERSION = P.CURRENTVERSIONNO
    ) SC
    LEFT JOIN dbo.STUDY_PLAN_CATALOG_ROLLUP R
        ON R.PLANID = P.PLANID
       AND R.PLANVERSION = P.CURRENTVERSIONNO
       AND R.ISACTIVE = 1
    WHERE P.CREATORUSERID = @CREATORUSERID
    ORDER BY P.CREATEDDATE DESC;
END
GO

-- ------------------------------------------------------------
-- USP_CATALOG_SEARCH (patched — include CREATORUSERID + bio)
-- ------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[USP_CATALOG_SEARCH]
(
    @SEARCHTERM NVARCHAR(200) = NULL,
    @TAGS       NVARCHAR(500) = NULL,
    @CATEGORY   NVARCHAR(50)  = NULL,
    @DIFFICULTY NVARCHAR(20)  = NULL,
    @SORTBY     NVARCHAR(20)  = 'RECENT',
    @PAGESIZE   INT           = 20,
    @PAGENUMBER INT           = 1
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @OFFSET INT = (@PAGENUMBER - 1) * @PAGESIZE;

    DECLARE @TAGFILTER TABLE (TAG NVARCHAR(100));
    IF @TAGS IS NOT NULL
    BEGIN
        INSERT INTO @TAGFILTER (TAG)
        SELECT TRIM(value) FROM STRING_SPLIT(@TAGS, ',')
        WHERE TRIM(value) != '';
    END

    ;WITH Base AS (
        SELECT
            P.PLANID, P.CREATORUSERID, P.TITLE, P.SHORTDESCRIPTION, P.CATEGORY,
            P.DIFFICULTY, P.DURATIONDAYS, P.THEMECOLORHEX,
            P.COVERFILEUUID, P.PLANICONEMOJI,
            P.PUBLISHEDAT, P.CREATEDDATE,
            CP.DISPLAYNAME  AS CREATORDISPLAYNAME,
            CP.AVATARFILEUUID AS CREATORAVATAR,
            CP.PUBLICEMAIL AS CREATORPUBLICEMAIL,
            CP.BIO AS CREATORBIO,
            R.AVGRATING, R.REVIEWCOUNT, R.ENROLLCOUNT, R.COMPLETIONPERCENT
        FROM dbo.STUDY_PLAN P
        LEFT JOIN dbo.CREATOR_PROFILE CP ON P.CREATORUSERID = CP.USERID
        LEFT JOIN dbo.STUDY_PLAN_CATALOG_ROLLUP R
            ON P.PLANID = R.PLANID AND R.PLANVERSION = P.CURRENTVERSIONNO AND R.ISACTIVE = 1
        WHERE P.PLANSTATUS = 'PUBLISHED'
          AND (@SEARCHTERM IS NULL
               OR P.TITLE LIKE '%' + @SEARCHTERM + '%'
               OR P.SHORTDESCRIPTION LIKE '%' + @SEARCHTERM + '%')
          AND (@CATEGORY IS NULL OR P.CATEGORY = @CATEGORY)
          AND (@DIFFICULTY IS NULL OR P.DIFFICULTY = @DIFFICULTY)
          AND (
              @TAGS IS NULL
              OR EXISTS (
                  SELECT 1 FROM dbo.STUDY_PLAN_TAG T
                  WHERE T.PLANID = P.PLANID AND T.TAG IN (SELECT TAG FROM @TAGFILTER)
              )
          )
    )
    SELECT
        COUNT(*) OVER() AS TOTALCOUNT,
        PLANID, CREATORUSERID, TITLE, SHORTDESCRIPTION, CATEGORY,
        DIFFICULTY, DURATIONDAYS, THEMECOLORHEX,
        COVERFILEUUID, PLANICONEMOJI,
        PUBLISHEDAT, CREATEDDATE,
        CREATORDISPLAYNAME, CREATORAVATAR, CREATORPUBLICEMAIL, CREATORBIO,
        AVGRATING, REVIEWCOUNT, ENROLLCOUNT, COMPLETIONPERCENT
    FROM Base
    ORDER BY
        CASE @SORTBY
            WHEN 'RATING'  THEN AVGRATING
            WHEN 'POPULAR' THEN CAST(ENROLLCOUNT AS DECIMAL(18,2))
            ELSE NULL
        END DESC,
        CASE WHEN @SORTBY = 'RECENT' THEN PUBLISHEDAT END DESC,
        PLANID DESC
    OFFSET @OFFSET ROWS FETCH NEXT @PAGESIZE ROWS ONLY;
END
GO

-- ------------------------------------------------------------
-- USP_CATALOG_GET_PLAN_PUBLIC (patched — creator bio)
-- ------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[USP_CATALOG_GET_PLAN_PUBLIC]
(
    @PLANID BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @STATUS NVARCHAR(30);
    DECLARE @PLANVERSION INT;

    SELECT @STATUS = PLANSTATUS, @PLANVERSION = CURRENTVERSIONNO
    FROM dbo.STUDY_PLAN
    WHERE PLANID = @PLANID;

    IF @STATUS IS NULL
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan not found' AS MESSAGE;
        RETURN;
    END

    IF @STATUS != 'PUBLISHED'
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan is not published' AS MESSAGE;
        RETURN;
    END

    SELECT
        P.PLANID, P.CREATORUSERID, P.TITLE, P.SHORTDESCRIPTION, P.FULLDESCRIPTION,
        P.DURATIONDAYS, P.CATEGORY, P.DIFFICULTY, P.THEMECOLORHEX,
        P.COVERFILEUUID, P.BANNERFILEUUID, P.PLANICONEMOJI,
        P.PLANSTATUS, P.CURRENTVERSIONNO, P.PUBLISHEDAT,
        CP.DISPLAYNAME  AS CREATORDISPLAYNAME,
        CP.AVATARFILEUUID AS CREATORAVATAR,
        CP.PUBLICEMAIL  AS CREATORPUBLICEMAIL,
        CP.BIO AS CREATORBIO,
        R.AVGRATING, R.REVIEWCOUNT, R.ENROLLCOUNT, R.COMPLETIONPERCENT
    FROM dbo.STUDY_PLAN P
    LEFT JOIN dbo.CREATOR_PROFILE CP ON P.CREATORUSERID = CP.USERID
    LEFT JOIN dbo.STUDY_PLAN_CATALOG_ROLLUP R
        ON P.PLANID = R.PLANID AND R.PLANVERSION = P.CURRENTVERSIONNO AND R.ISACTIVE = 1
    WHERE P.PLANID = @PLANID;

    SELECT TAG
    FROM dbo.STUDY_PLAN_TAG
    WHERE PLANID = @PLANID;

    SELECT
        D.DAYID, D.DAYNUMBER, D.TITLE, D.NOTES
    FROM dbo.STUDY_PLAN_DAY D
    WHERE D.PLANID = @PLANID AND D.PLANVERSION = @PLANVERSION
    ORDER BY D.DAYNUMBER ASC;

    SELECT
        S.SLOTID, S.DAYID, S.SLOTTYPE, S.TITLE, S.DESCRIPTION,
        S.ESTIMATEDMINUTES, S.SORTORDER, S.TOPICID, S.CONTENTID,
        S.CONTENTFILEUUID, S.EXTERNALURL, S.QUIZJSON
    FROM dbo.STUDY_PLAN_SLOT S
    INNER JOIN dbo.STUDY_PLAN_DAY D ON S.DAYID = D.DAYID
    WHERE D.PLANID = @PLANID AND D.PLANVERSION = @PLANVERSION
    ORDER BY D.DAYNUMBER ASC, S.SORTORDER ASC;
END
GO

-- ------------------------------------------------------------
-- Backfill CREATOR_PROFILE for approved apps / published plans
-- Safe to re-run (IF NOT EXISTS).
-- ------------------------------------------------------------
INSERT INTO dbo.CREATOR_PROFILE
(
    USERID, DISPLAYNAME, BIO, EXPERTISETAGS, PUBLICEMAIL,
    AVATARFILEUUID, COVERFILEUUID, WEBSITEURL,
    PROFILESTATUS, CREATEDDATE, UPDATEDDATE
)
SELECT
    A.USERID,
    COALESCE(NULLIF(LTRIM(RTRIM(A.DISPLAYNAMEPREF)), N''),
             N'Creator ' + CAST(A.USERID AS NVARCHAR(30))),
    A.BIODRAFT,
    NULL, NULL, NULL, NULL, NULL,
    N'ACTIVE',
    SYSUTCDATETIME(),
    SYSUTCDATETIME()
FROM dbo.CREATOR_APPLICATION A
WHERE A.ACTIVE = 1
  AND A.STATUS = N'APPROVED'
  AND NOT EXISTS (
      SELECT 1 FROM dbo.CREATOR_PROFILE P WHERE P.USERID = A.USERID
  );

INSERT INTO dbo.CREATOR_PROFILE
(
    USERID, DISPLAYNAME, BIO, EXPERTISETAGS, PUBLICEMAIL,
    AVATARFILEUUID, COVERFILEUUID, WEBSITEURL,
    PROFILESTATUS, CREATEDDATE, UPDATEDDATE
)
SELECT DISTINCT
    P.CREATORUSERID,
    N'Creator ' + CAST(P.CREATORUSERID AS NVARCHAR(30)),
    NULL, NULL, NULL, NULL, NULL, NULL,
    N'ACTIVE',
    SYSUTCDATETIME(),
    SYSUTCDATETIME()
FROM dbo.STUDY_PLAN P
WHERE P.PLANSTATUS IN (N'PUBLISHED', N'UNLISTED')
  AND NOT EXISTS (
      SELECT 1 FROM dbo.CREATOR_PROFILE CP WHERE CP.USERID = P.CREATORUSERID
  );
GO
