-- Phase 1: Creator slot retention config (backward compatible defaults)
USE [CREATOR_SERVICE]
GO

IF COL_LENGTH('dbo.STUDY_PLAN_SLOT', 'REQUIRESREVIEW') IS NULL
BEGIN
    ALTER TABLE dbo.STUDY_PLAN_SLOT ADD
        REQUIRESREVIEW          BIT            NOT NULL CONSTRAINT DF_SPS_REQUIRESREVIEW DEFAULT (0),
        REVIEWMETHOD            NVARCHAR(32)   NULL,
        REVIEWDIFFICULTY        NVARCHAR(16)   NULL,
        ESTIMATEDRECALLMINUTES  INT            NULL,
        REVIEWTEMPLATE          NVARCHAR(32)   NULL,
        REVIEWCONFIGJSON        NVARCHAR(MAX)  NULL;
END
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_STUDY_PLAN_SLOT_UPSERT]
(
    @SLOTID          BIGINT         = NULL,
    @DAYID           BIGINT         = NULL,
    @PLANID          BIGINT,
    @CREATORUSERID   BIGINT,
    @SLOTTYPE        NVARCHAR(20)   = NULL,
    @TITLE           NVARCHAR(200)  = NULL,
    @DESCRIPTION     NVARCHAR(MAX)  = NULL,
    @ESTIMATEDMINUTES INT           = NULL,
    @SORTORDER       INT            = NULL,
    @TOPICID         INT            = NULL,
    @CONTENTID       INT            = NULL,
    @CONTENTFILEUUID NVARCHAR(100)  = NULL,
    @EXTERNALURL     NVARCHAR(2000) = NULL,
    @QUIZJSON        NVARCHAR(MAX)  = NULL,
    @REQUIRESREVIEW  BIT            = NULL,
    @REVIEWMETHOD    NVARCHAR(32)   = NULL,
    @REVIEWDIFFICULTY NVARCHAR(16)  = NULL,
    @ESTIMATEDRECALLMINUTES INT     = NULL,
    @REVIEWTEMPLATE  NVARCHAR(32)   = NULL,
    @REVIEWCONFIGJSON NVARCHAR(MAX) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        DECLARE @OWNERID     BIGINT;
        DECLARE @STATUS      NVARCHAR(30);
        DECLARE @PLANVERSION INT;

        SELECT @OWNERID     = CREATORUSERID,
               @STATUS      = PLANSTATUS,
               @PLANVERSION = CURRENTVERSIONNO
        FROM dbo.STUDY_PLAN
        WHERE PLANID = @PLANID;

        IF @OWNERID IS NULL
        BEGIN
            SELECT 0 AS SUCCESS, NULL AS SLOTID, NULL AS SORTORDER,
                   'Plan not found' AS MESSAGE;
            RETURN;
        END

        IF @OWNERID != @CREATORUSERID
        BEGIN
            SELECT 0 AS SUCCESS, NULL AS SLOTID, NULL AS SORTORDER,
                   'You do not own this plan' AS MESSAGE;
            RETURN;
        END

        IF @STATUS != 'DRAFT'
        BEGIN
            SELECT 0 AS SUCCESS, NULL AS SLOTID, NULL AS SORTORDER,
                   'Plan must be in DRAFT status' AS MESSAGE;
            RETURN;
        END

        IF @SLOTID IS NOT NULL
        BEGIN
            IF @DAYID IS NULL
            BEGIN
                SELECT @DAYID = DAYID FROM dbo.STUDY_PLAN_SLOT
                WHERE SLOTID = @SLOTID;
            END

            IF @DAYID IS NULL OR NOT EXISTS (
                SELECT 1 FROM dbo.STUDY_PLAN_SLOT S
                INNER JOIN dbo.STUDY_PLAN_DAY D ON S.DAYID = D.DAYID
                WHERE S.SLOTID = @SLOTID AND D.PLANID = @PLANID
            )
            BEGIN
                SELECT 0 AS SUCCESS, NULL AS SLOTID, NULL AS SORTORDER,
                       'Slot not found in this plan' AS MESSAGE;
                RETURN;
            END

            UPDATE dbo.STUDY_PLAN_SLOT
            SET SLOTTYPE         = COALESCE(@SLOTTYPE, SLOTTYPE),
                TITLE            = COALESCE(@TITLE, TITLE),
                DESCRIPTION      = CASE WHEN @DESCRIPTION IS NULL THEN DESCRIPTION ELSE @DESCRIPTION END,
                ESTIMATEDMINUTES = CASE WHEN @ESTIMATEDMINUTES IS NULL THEN ESTIMATEDMINUTES ELSE @ESTIMATEDMINUTES END,
                SORTORDER        = COALESCE(@SORTORDER, SORTORDER),
                TOPICID          = CASE WHEN @TOPICID IS NULL THEN TOPICID ELSE @TOPICID END,
                CONTENTID        = CASE WHEN @CONTENTID IS NULL THEN CONTENTID ELSE @CONTENTID END,
                CONTENTFILEUUID  = CASE WHEN @CONTENTFILEUUID IS NULL THEN CONTENTFILEUUID ELSE @CONTENTFILEUUID END,
                EXTERNALURL      = CASE WHEN @EXTERNALURL IS NULL THEN EXTERNALURL ELSE @EXTERNALURL END,
                QUIZJSON         = CASE WHEN @QUIZJSON IS NULL THEN QUIZJSON ELSE @QUIZJSON END,
                REQUIRESREVIEW   = CASE WHEN @REQUIRESREVIEW IS NULL THEN REQUIRESREVIEW ELSE @REQUIRESREVIEW END,
                REVIEWMETHOD     = CASE WHEN @REVIEWMETHOD IS NULL THEN REVIEWMETHOD ELSE @REVIEWMETHOD END,
                REVIEWDIFFICULTY = CASE WHEN @REVIEWDIFFICULTY IS NULL THEN REVIEWDIFFICULTY ELSE @REVIEWDIFFICULTY END,
                ESTIMATEDRECALLMINUTES = CASE
                    WHEN @ESTIMATEDRECALLMINUTES IS NULL THEN ESTIMATEDRECALLMINUTES
                    ELSE @ESTIMATEDRECALLMINUTES END,
                REVIEWTEMPLATE   = CASE WHEN @REVIEWTEMPLATE IS NULL THEN REVIEWTEMPLATE ELSE @REVIEWTEMPLATE END,
                REVIEWCONFIGJSON = CASE WHEN @REVIEWCONFIGJSON IS NULL THEN REVIEWCONFIGJSON ELSE @REVIEWCONFIGJSON END,
                UPDATEDDATE      = SYSUTCDATETIME()
            WHERE SLOTID = @SLOTID AND DAYID = @DAYID;

            DECLARE @UPDATEDSORTORDER INT;
            SELECT @UPDATEDSORTORDER = SORTORDER
            FROM dbo.STUDY_PLAN_SLOT WHERE SLOTID = @SLOTID;

            SELECT 1 AS SUCCESS, @SLOTID AS SLOTID,
                   @UPDATEDSORTORDER AS SORTORDER, 'Slot updated' AS MESSAGE;
            RETURN;
        END

        IF @DAYID IS NULL
        BEGIN
            SELECT 0 AS SUCCESS, NULL AS SLOTID, NULL AS SORTORDER,
                   'dayId is required to create a slot' AS MESSAGE;
            RETURN;
        END

        IF NOT EXISTS (
            SELECT 1 FROM dbo.STUDY_PLAN_DAY
            WHERE DAYID = @DAYID AND PLANID = @PLANID
        )
        BEGIN
            SELECT 0 AS SUCCESS, NULL AS SLOTID, NULL AS SORTORDER,
                   'Day not found in this plan' AS MESSAGE;
            RETURN;
        END

        DECLARE @EFFECTIVETYPE  NVARCHAR(20) = COALESCE(NULLIF(@SLOTTYPE, N''), N'CUSTOM');
        DECLARE @EFFECTIVETITLE NVARCHAR(200) = NULLIF(@TITLE, N'');

        IF @EFFECTIVETITLE IS NULL
        BEGIN
            SELECT 0 AS SUCCESS, NULL AS SLOTID, NULL AS SORTORDER,
                   'title is required' AS MESSAGE;
            RETURN;
        END

        DECLARE @EFFECTIVESORTORDER INT;
        IF @SORTORDER IS NULL
            SELECT @EFFECTIVESORTORDER = ISNULL(MAX(SORTORDER), -1) + 1
            FROM dbo.STUDY_PLAN_SLOT WHERE DAYID = @DAYID;
        ELSE
            SET @EFFECTIVESORTORDER = @SORTORDER;

        INSERT INTO dbo.STUDY_PLAN_SLOT
        (
            DAYID, PLANVERSION, SLOTTYPE, TITLE, DESCRIPTION,
            ESTIMATEDMINUTES, SORTORDER, TOPICID, CONTENTID,
            CONTENTFILEUUID, EXTERNALURL, QUIZJSON,
            REQUIRESREVIEW, REVIEWMETHOD, REVIEWDIFFICULTY,
            ESTIMATEDRECALLMINUTES, REVIEWTEMPLATE, REVIEWCONFIGJSON,
            CREATEDDATE, UPDATEDDATE
        )
        VALUES
        (
            @DAYID, @PLANVERSION, @EFFECTIVETYPE, @EFFECTIVETITLE, @DESCRIPTION,
            @ESTIMATEDMINUTES, @EFFECTIVESORTORDER, @TOPICID, @CONTENTID,
            @CONTENTFILEUUID, @EXTERNALURL, @QUIZJSON,
            ISNULL(@REQUIRESREVIEW, 0), @REVIEWMETHOD, @REVIEWDIFFICULTY,
            @ESTIMATEDRECALLMINUTES, @REVIEWTEMPLATE, @REVIEWCONFIGJSON,
            SYSUTCDATETIME(), SYSUTCDATETIME()
        );

        SET @SLOTID = SCOPE_IDENTITY();

        SELECT 1 AS SUCCESS, @SLOTID AS SLOTID,
               @EFFECTIVESORTORDER AS SORTORDER, 'Slot created' AS MESSAGE;
    END TRY
    BEGIN CATCH
        SELECT 0 AS SUCCESS, NULL AS SLOTID, NULL AS SORTORDER,
               ERROR_MESSAGE() AS MESSAGE;
    END CATCH
END
GO
