-- Phase A/D: Creator plan progression mode (CREATOR_SERVICE)
USE [CREATOR_SERVICE]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF COL_LENGTH('dbo.STUDY_PLAN', 'PROGRESSIONMODE') IS NULL
BEGIN
    ALTER TABLE dbo.STUDY_PLAN ADD
        PROGRESSIONMODE NVARCHAR(32) NOT NULL
            CONSTRAINT DF_STUDY_PLAN_PROGMODE DEFAULT (N'DAILY_GUIDED'),
        UNLOCKTIMELOCAL TIME(0) NULL,
        SCHEDULEJSON NVARCHAR(MAX) NULL;
END
GO

-- Existing published catalog courses: grandfather SELF_PACED so current
-- learners/creators keep binge-unlock behavior. New drafts default DAILY_GUIDED.
UPDATE dbo.STUDY_PLAN
SET PROGRESSIONMODE = N'SELF_PACED'
WHERE PLANSTATUS = N'PUBLISHED';
GO

-- Persist progression mode on create/update/detail
CREATE OR ALTER PROCEDURE [dbo].[USP_STUDY_PLAN_CREATE]
(
    @CREATORUSERID    BIGINT,
    @TITLE            NVARCHAR(200),
    @SHORTDESCRIPTION NVARCHAR(500)  = NULL,
    @FULLDESCRIPTION  NVARCHAR(MAX)  = NULL,
    @DURATIONDAYS     INT            = NULL,
    @CATEGORY         NVARCHAR(50)   = NULL,
    @DIFFICULTY       NVARCHAR(20)   = NULL,
    @THEMECOLORHEX    NVARCHAR(20)   = NULL,
    @COVERFILEUUID    NVARCHAR(100)  = NULL,
    @BANNERFILEUUID   NVARCHAR(100)  = NULL,
    @PLANICONEMOJI    NVARCHAR(50)   = NULL,
    @PROGRESSIONMODE  NVARCHAR(32)   = N'DAILY_GUIDED',
    @UNLOCKTIMELOCAL  TIME(0)        = NULL,
    @SCHEDULEJSON     NVARCHAR(MAX)  = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @PLANID BIGINT;
        DECLARE @MODE NVARCHAR(32) = UPPER(ISNULL(NULLIF(LTRIM(RTRIM(@PROGRESSIONMODE)), N''), N'DAILY_GUIDED'));
        IF @MODE NOT IN (N'SELF_PACED', N'DAILY_GUIDED', N'WEEKLY', N'SCHEDULED', N'COHORT')
            SET @MODE = N'DAILY_GUIDED';

        INSERT INTO dbo.STUDY_PLAN
        (
            CREATORUSERID, TITLE, SHORTDESCRIPTION, FULLDESCRIPTION,
            DURATIONDAYS, CATEGORY, DIFFICULTY, THEMECOLORHEX,
            COVERFILEUUID, BANNERFILEUUID, PLANICONEMOJI,
            PROGRESSIONMODE, UNLOCKTIMELOCAL, SCHEDULEJSON,
            PLANSTATUS, CURRENTVERSIONNO, CREATEDDATE, UPDATEDDATE
        )
        VALUES
        (
            @CREATORUSERID, @TITLE, @SHORTDESCRIPTION, @FULLDESCRIPTION,
            @DURATIONDAYS, @CATEGORY, @DIFFICULTY, @THEMECOLORHEX,
            @COVERFILEUUID, @BANNERFILEUUID, @PLANICONEMOJI,
            @MODE, @UNLOCKTIMELOCAL, @SCHEDULEJSON,
            'DRAFT', 1, SYSUTCDATETIME(), SYSUTCDATETIME()
        );

        SET @PLANID = SCOPE_IDENTITY();

        INSERT INTO dbo.STUDY_PLAN_VERSION (PLANID, VERSIONNO, CHANGENOTES, CREATEDDATE)
        VALUES (@PLANID, 1, 'Initial version', SYSUTCDATETIME());

        COMMIT TRANSACTION;

        SELECT 1 AS SUCCESS, @PLANID AS PLANID, 'Plan created' AS MESSAGE;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        SELECT 0 AS SUCCESS, NULL AS PLANID, ERROR_MESSAGE() AS MESSAGE;
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE [dbo].[USP_STUDY_PLAN_UPDATE_METADATA]
(
    @PLANID           BIGINT,
    @CREATORUSERID    BIGINT,
    @TITLE            NVARCHAR(200)  = NULL,
    @SHORTDESCRIPTION NVARCHAR(500)  = NULL,
    @FULLDESCRIPTION  NVARCHAR(MAX)  = NULL,
    @DURATIONDAYS     INT            = NULL,
    @CATEGORY         NVARCHAR(50)   = NULL,
    @DIFFICULTY       NVARCHAR(20)   = NULL,
    @THEMECOLORHEX    NVARCHAR(20)   = NULL,
    @COVERFILEUUID    NVARCHAR(100)  = NULL,
    @BANNERFILEUUID   NVARCHAR(100)  = NULL,
    @PLANICONEMOJI    NVARCHAR(50)   = NULL,
    @PROGRESSIONMODE  NVARCHAR(32)   = NULL,
    @UNLOCKTIMELOCAL  TIME(0)        = NULL,
    @SCHEDULEJSON     NVARCHAR(MAX)  = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        DECLARE @OWNERID BIGINT;
        DECLARE @STATUS NVARCHAR(30);

        SELECT @OWNERID = CREATORUSERID, @STATUS = PLANSTATUS
        FROM dbo.STUDY_PLAN
        WHERE PLANID = @PLANID;

        IF @OWNERID IS NULL
        BEGIN
            SELECT 0 AS SUCCESS, 'Plan not found' AS MESSAGE;
            RETURN;
        END

        IF @OWNERID != @CREATORUSERID
        BEGIN
            SELECT 0 AS SUCCESS, 'You do not own this plan' AS MESSAGE;
            RETURN;
        END

        IF @STATUS != 'DRAFT'
        BEGIN
            SELECT 0 AS SUCCESS, 'Plan must be in DRAFT status to edit metadata' AS MESSAGE;
            RETURN;
        END

        DECLARE @MODE NVARCHAR(32) = NULL;
        IF @PROGRESSIONMODE IS NOT NULL AND LTRIM(RTRIM(@PROGRESSIONMODE)) <> N''
        BEGIN
            SET @MODE = UPPER(LTRIM(RTRIM(@PROGRESSIONMODE)));
            IF @MODE NOT IN (N'SELF_PACED', N'DAILY_GUIDED', N'WEEKLY', N'SCHEDULED', N'COHORT')
                SET @MODE = NULL;
        END

        UPDATE dbo.STUDY_PLAN
        SET TITLE             = COALESCE(@TITLE, TITLE),
            SHORTDESCRIPTION  = COALESCE(@SHORTDESCRIPTION, SHORTDESCRIPTION),
            FULLDESCRIPTION   = COALESCE(@FULLDESCRIPTION, FULLDESCRIPTION),
            DURATIONDAYS      = COALESCE(@DURATIONDAYS, DURATIONDAYS),
            CATEGORY          = COALESCE(@CATEGORY, CATEGORY),
            DIFFICULTY        = COALESCE(@DIFFICULTY, DIFFICULTY),
            THEMECOLORHEX     = COALESCE(@THEMECOLORHEX, THEMECOLORHEX),
            COVERFILEUUID     = COALESCE(@COVERFILEUUID, COVERFILEUUID),
            BANNERFILEUUID    = COALESCE(@BANNERFILEUUID, BANNERFILEUUID),
            PLANICONEMOJI     = COALESCE(@PLANICONEMOJI, PLANICONEMOJI),
            PROGRESSIONMODE   = COALESCE(@MODE, PROGRESSIONMODE),
            UNLOCKTIMELOCAL   = COALESCE(@UNLOCKTIMELOCAL, UNLOCKTIMELOCAL),
            SCHEDULEJSON      = COALESCE(@SCHEDULEJSON, SCHEDULEJSON),
            UPDATEDDATE       = SYSUTCDATETIME()
        WHERE PLANID = @PLANID;

        SELECT 1 AS SUCCESS, 'Plan metadata updated' AS MESSAGE;
    END TRY
    BEGIN CATCH
        SELECT 0 AS SUCCESS, ERROR_MESSAGE() AS MESSAGE;
    END CATCH
END
GO

-- Catalog public detail: expose progression fields for enroll snapshot
CREATE OR ALTER PROCEDURE [dbo].[USP_CATALOG_GET_PLAN_PUBLIC]
(
    @PLANID BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @STATUS NVARCHAR(30);
    DECLARE @PLANVERSION INT;

    SELECT @STATUS = PLANSTATUS, @PLANVERSION = CURRENTVERSIONNO
    FROM dbo.STUDY_PLAN
    WHERE PLANID = @PLANID;

    IF @STATUS IS NULL
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan not found' AS MESSAGE;
        RETURN;
    END

    IF @STATUS != 'PUBLISHED'
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan is not published' AS MESSAGE;
        RETURN;
    END

    SELECT
        P.PLANID, P.CREATORUSERID, P.TITLE, P.SHORTDESCRIPTION, P.FULLDESCRIPTION,
        P.DURATIONDAYS, P.CATEGORY, P.DIFFICULTY, P.THEMECOLORHEX,
        P.COVERFILEUUID, P.BANNERFILEUUID, P.PLANICONEMOJI,
        P.PROGRESSIONMODE, P.UNLOCKTIMELOCAL, P.SCHEDULEJSON,
        P.PLANSTATUS, P.CURRENTVERSIONNO, P.PUBLISHEDAT,
        CP.DISPLAYNAME  AS CREATORDISPLAYNAME,
        CP.AVATARFILEUUID AS CREATORAVATAR,
        CP.PUBLICEMAIL  AS CREATORPUBLICEMAIL,
        CP.BIO AS CREATORBIO,
        R.AVGRATING, R.REVIEWCOUNT, R.ENROLLCOUNT, R.COMPLETIONPERCENT
    FROM dbo.STUDY_PLAN P
    LEFT JOIN dbo.CREATOR_PROFILE CP ON P.CREATORUSERID = CP.USERID
    LEFT JOIN dbo.STUDY_PLAN_CATALOG_ROLLUP R
        ON P.PLANID = R.PLANID AND R.PLANVERSION = P.CURRENTVERSIONNO AND R.ISACTIVE = 1
    WHERE P.PLANID = @PLANID;

    SELECT TAG
    FROM dbo.STUDY_PLAN_TAG
    WHERE PLANID = @PLANID;

    SELECT
        D.DAYID, D.DAYNUMBER, D.TITLE, D.NOTES
    FROM dbo.STUDY_PLAN_DAY D
    WHERE D.PLANID = @PLANID AND D.PLANVERSION = @PLANVERSION
    ORDER BY D.DAYNUMBER ASC;

    SELECT
        S.SLOTID, S.DAYID, S.SLOTTYPE, S.TITLE, S.DESCRIPTION,
        S.ESTIMATEDMINUTES, S.SORTORDER, S.TOPICID, S.CONTENTID,
        S.CONTENTFILEUUID, S.EXTERNALURL, S.QUIZJSON
    FROM dbo.STUDY_PLAN_SLOT S
    INNER JOIN dbo.STUDY_PLAN_DAY D ON S.DAYID = D.DAYID
    WHERE D.PLANID = @PLANID AND D.PLANVERSION = @PLANVERSION
    ORDER BY D.DAYNUMBER ASC, S.SORTORDER ASC;
END
GO

-- Soft mode validation on publish: SCHEDULED/COHORT need SCHEDULEJSON
CREATE OR ALTER PROCEDURE [dbo].[USP_STUDY_PLAN_PUBLISH_VALIDATE]
(
    @PLANID        BIGINT,
    @CREATORUSERID BIGINT
)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @OWNERID BIGINT;
    DECLARE @STATUS  NVARCHAR(30);
    DECLARE @PLANVERSION INT;
    DECLARE @DURATIONDAYS INT;
    DECLARE @PROGRESSIONMODE NVARCHAR(32);
    DECLARE @SCHEDULEJSON NVARCHAR(MAX);

    SELECT @OWNERID = CREATORUSERID,
           @STATUS  = PLANSTATUS,
           @PLANVERSION = CURRENTVERSIONNO,
           @DURATIONDAYS = DURATIONDAYS,
           @PROGRESSIONMODE = UPPER(ISNULL(PROGRESSIONMODE, N'DAILY_GUIDED')),
           @SCHEDULEJSON = SCHEDULEJSON
    FROM dbo.STUDY_PLAN
    WHERE PLANID = @PLANID;

    IF @OWNERID IS NULL
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan not found' AS MESSAGE;
        RETURN;
    END

    IF @OWNERID != @CREATORUSERID
    BEGIN
        SELECT 0 AS SUCCESS, 'You do not own this plan' AS MESSAGE;
        RETURN;
    END

    IF @STATUS NOT IN ('DRAFT', 'READY_FOR_REVIEW')
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan must be in DRAFT or READY_FOR_REVIEW status' AS MESSAGE;
        RETURN;
    END

    IF NOT EXISTS (
        SELECT 1
        FROM dbo.CREATOR_PROFILE
        WHERE USERID = @CREATORUSERID
          AND PROFILESTATUS = N'ACTIVE'
          AND DISPLAYNAME IS NOT NULL
          AND LTRIM(RTRIM(DISPLAYNAME)) <> N''
    )
    BEGIN
        SELECT 0 AS SUCCESS,
               'Create your creator profile with a display name before publishing' AS MESSAGE;
        RETURN;
    END

    DECLARE @DAYCOUNT INT;
    SELECT @DAYCOUNT = COUNT(*)
    FROM dbo.STUDY_PLAN_DAY
    WHERE PLANID = @PLANID AND PLANVERSION = @PLANVERSION;

    IF @DAYCOUNT = 0
    BEGIN
        SELECT 0 AS SUCCESS, 'Plan has 0 days' AS MESSAGE;
        RETURN;
    END

    DECLARE @EMPTYDAY INT;
    DECLARE @EMPTYDAYNUMBER INT;

    SELECT TOP 1 @EMPTYDAY = D.DAYID, @EMPTYDAYNUMBER = D.DAYNUMBER
    FROM dbo.STUDY_PLAN_DAY D
    LEFT JOIN dbo.STUDY_PLAN_SLOT S ON D.DAYID = S.DAYID
    WHERE D.PLANID = @PLANID AND D.PLANVERSION = @PLANVERSION
    GROUP BY D.DAYID, D.DAYNUMBER
    HAVING COUNT(S.SLOTID) = 0
    ORDER BY D.DAYNUMBER ASC;

    IF @EMPTYDAY IS NOT NULL
    BEGIN
        SELECT 0 AS SUCCESS,
               'Day ' + CAST(@EMPTYDAYNUMBER AS NVARCHAR(10)) + ' has no slots' AS MESSAGE;
        RETURN;
    END

    IF @DURATIONDAYS IS NOT NULL AND @DURATIONDAYS != @DAYCOUNT
    BEGIN
        SELECT 0 AS SUCCESS,
               'DURATIONDAYS (' + CAST(@DURATIONDAYS AS NVARCHAR(10))
               + ') does not match actual day count ('
               + CAST(@DAYCOUNT AS NVARCHAR(10)) + ')' AS MESSAGE;
        RETURN;
    END

    IF @PROGRESSIONMODE IN (N'SCHEDULED', N'COHORT')
       AND ( @SCHEDULEJSON IS NULL OR LTRIM(RTRIM(@SCHEDULEJSON)) = N''
             OR LTRIM(RTRIM(@SCHEDULEJSON)) IN (N'{}', N'[]', N'null') )
    BEGIN
        SELECT 0 AS SUCCESS,
               'SCHEDULED/COHORT plans require scheduleJson before publish' AS MESSAGE;
        RETURN;
    END

    SELECT 1 AS SUCCESS, 'Validation passed' AS MESSAGE;
END
GO
